export const LaptopProductDb=[
    {
        "no": 69,
        "id": "c1-laptop",
        "productname": " DELL XPS 17",
        "productprice": "1,555,000",
        "productinfo": "DELL XPS 17 9700 10th generation laptop",
        "productimage1": "/skydome images/c1-laptop-img.jpeg",
        "productimage2": "/skydome images/c1-laptop-img2.jpeg",
        "processortype": "intel",
        "processorname": "core19",
        "brand": "DELL",
        "batteryinfo": "Primary Battery 6-Cell Battery, 97WHr (Integrated)",
        "ram": "32",
        "rom": "1tb ssd",
        "windowversion": "windows 10 pro",
        "color": "silver",
        "touchscreen": "no",
        "netweight": "2.51kg",
        "inch": "17.0",
        "gaminggraphics": "NVIDIA GeForce RTX 2060 6GB GDDR6 with Max-Q",
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Dell xps 32gb ram 1tb ssd,windows 10, core 19..."
    },
    {
        "no": 71,
        "id": "c2-laptop",
        "productname": "DELL G5 Gamming pc",
        "productprice": "460,000",
        "productinfo": "DELL G5 Gamming 10th generation laptop",
        "productimage1": "/skydome images/c2-laptop-img1.jpeg",
        "productimage2": "/skydome images/c2-laptop-img2.jpeg",
        "processortype": "intel",
        "processorname": "core15",
        "brand": "DELL",
        "batteryinfo": "Li-polymer 15.2v 68Wh 4-cell battery",
        "ram": "8",
        "rom": "256 ssd",
        "windowversion": "windows 10 pro",
        "color": "black",
        "touchscreen": "no",
        "netweight": "2.8kg",
        "inch": "15.6",
        "gaminggraphics": "4gb ram NVIDIA GeForce GTX 1650Ti",
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Dell G5 gamming laptop 8gb ram,256gb ssd,windows 10h"
    },
    {
        "no": 72,
        "id": "c3-laptop",
        "productname": "Asus X515JA",
        "productprice": "214,000",
        "productinfo": "Asus X515JA laptop",
        "productimage1": "/skydome images/c3-laptop-img1.jpeg",
        "productimage2": "/skydome images/c3-laptop-img2.jpeg",
        "processortype": "intel",
        "processorname": "core13",
        "brand": "ASUS",
        "batteryinfo": "Lithium Battery Energy Content ?37 Watt Hours 2 ion cells",
        "ram": "4",
        "rom": "1tb ssd",
        "windowversion": "windows 10",
        "color": "Transparent silver",
        "touchscreen": "no",
        "netweight": "1.7kg",
        "inch": "15.6",
        "gaminggraphics": "intel graphics card",
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Asus x515ja ,4gb ram,1tb hdd,windows 10,core i3"
    },
    {
        "no": 1,
        "id": "c1",
        "productname": "hp 250 g8",
        "productprice": "325,000",
        "productinfo": "hp 250 g8 10th generation laptop",
        "productimage1": "/skydome images/hp-250-g8-img1.jpeg",
        "productimage2": "/skydome images/hp-250-g8-img2.jpeg",
        "processortype": "intel",
        "processorname": "corei7",
        "brand": "hp",
        "batteryinfo": "45watt li-on battery",
        "ram": "8gb",
        "rom": "1tbhdd",
        "windowversion": "windows 10 pro",
        "color": "silver",
        "touchscreen": "no",
        "netweight": "1.3kg",
        "inch": "15",
        "gaminggraphics": "2gb dedicated gaming graphics",
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"hp 250 g8 laptop 8gb ram 1tb hdd windows 10pro core i5"
	
    },
    {
        "no": 3,
        "id": "c2",
        "productname": "lenovo legion 5",
        "productprice": "650,000",
        "productinfo": "lenovo legion 5 15IMH05 10th generation laptop",
        "productimage1": "/skydome images/lenovo-legion-5-img1.png",
        "productimage2": "/skydome images/lenovo-legion-5-img2.jpeg",
        "processortype": "intel",
        "processorname": "corei7",
        "brand": "lenovo",
        "batteryinfo": "integrated 60Wh",
        "ram": "8gb",
        "rom": "512gb ssd",
        "windowversion": "windows 10 home",
        "color": "black",
        "touchscreen": "no",
        "netweight": "1.3kg",
        "inch": "15.6",
        "gaminggraphics": "NVIDIA GTX 4GB GDDR6",
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"lenovo legion 5 core i5 8gb ram 512gb 4gb nivida win..."
    },
    {
        "no": 4,
        "id": "c3",
        "productname": "mac book pro",
        "productprice": "1,395,000",
        "productinfo": "apple mac book pro 16\" AMD Raedon Pro 5500M",
        "productimage1": "/skydome images/mac-book-pro-img2.jpeg",
        "productimage2": "/skydome images/mac-book-pro-img1.jpeg",
        "processortype": "intel",
        "processorname": "corei9",
        "brand": "Apple",
        "batteryinfo": "96W USB-C power adapter Up to 11 hours battery life",
        "ram": "16gb",
        "rom": "1tb ssd",
        "windowversion": "mac os",
        "color": "space grey",
        "touchscreen": "no",
        "netweight": "2kg",
        "inch": "14.09",
        "gaminggraphics": "AMD Radeon Pro 5500M graphics card With 4GB of GDDR6 VRAM",
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"apple mac book pro touch bar core i9 16gb 1tb ssd AMD..."
    },
    {
        "no": 6,
        "id": "c4",
        "productname": "acer predator helios",
        "productprice": "810,000",
        "productinfo": "acer predator helios 300",
        "productimage1": "/skydome images/acer-predator-helios-img2.jpeg",
        "productimage2": "/skydome images/acer-predator-helios-img1.jpeg",
        "processortype": "intel",
        "processorname": "corei7",
        "brand": "Acer",
        "batteryinfo": "Average Battery Life (in hours) ?6 Hours",
        "ram": "16gb",
        "rom": "512gb ssd",
        "windowversion": "windows 10",
        "color": "black",
        "touchscreen": "no",
        "netweight": "2.5kg",
        "inch": "15.6",
        "gaminggraphics": "Dedicated NVIDIA GeForce RTX 3060 6GB",
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"acer predator helios 300 corei7 16gb ram,..."
    },
    {
        "no": 73,
        "id": "c4-laptop",
        "productname": "Apple macbook air",
        "productprice": "590,000",
        "productinfo": "Apple macbook air laptop with M1 chip",
        "productimage1": "/skydome images/c4-laptop-img1.jpeg",
        "productimage2": "/skydome images/c4-laptop-img2.jpeg",
        "processortype": "Apple M1",
        "processorname": "core15",
        "brand": "Apple",
        "batteryinfo": "30W USB Type-C Power Adapter",
        "ram": "8gb",
        "rom": "256 ssd",
        "windowversion": "macOS Big Sur 11.0",
        "color": "space grey",
        "touchscreen": "no",
        "netweight": "0.7kg",
        "inch": "13",
        "gaminggraphics": "2gb ram",
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Apple macbook air 13' M1 chip core 15 8gb ram 256gb rom"
    },
    {
        "no": 74,
        "id": "c5-laptop",
        "productname": "Razer blade Stealth",
        "productprice": "682,000",
        "productinfo": "Razer Blade Stealth 13 GAMING laptop",
        "productimage1": "/skydome images/c5-laptop-img1.jpeg",
        "productimage2": "/skydome images/c5-laptop-img2.jpeg",
        "processortype": "intel",
        "processorname": "corei7",
        "brand": "Razer",
        "batteryinfo": "53.1Wh battery with up to 10hours battery life",
        "ram": "16gb",
        "rom": "256gb ssd",
        "windowversion": "windows 10",
        "color": "black",
        "touchscreen": "no",
        "netweight": "2.9kg",
        "inch": "13.3",
        "gaminggraphics": "NVIDIA GeForce GTX MX150 graphics card.",
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Razer Blade Stealth 13 GAMING laptop,core i7,16gb ram 256.."
    },
    {
        "no": 75,
        "id": "c6-laptop",
        "productname": "Lenovo v15",
        "productprice": "258,000",
        "productinfo": "Lenovo v15 laptop",
        "productimage1": "/skydome images/c6-laptop-img1.jpeg",
        "productimage2": "/skydome images/c6-laptop-img2.jpeg",
        "processortype": "intel",
        "processorname": "corei3",
        "brand": "Lenovo",
        "batteryinfo": "4 Lithium Ion Cells with up to 8hours",
        "ram": "26gb",
        "rom": "1tb hdd",
        "windowversion": "windows 10",
        "color": "black",
        "touchscreen": "no",
        "netweight": "1.1kg",
        "inch": "15.6",
        "gaminggraphics": "Intel HD Graphics 610",
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Lenovo V15 core i3 ,12gb ram,1tb hdd,windows 10..."
    },
    {
        "no": 76,
        "id": "c7-laptop",
        "productname": "Microsoft surface pro 6",
        "productprice": "645,000",
        "productinfo": "Microsoft surface pro 6 laptop",
        "productimage1": "/skydome images/c7-laptop-img1.jpeg",
        "productimage2": "/skydome images/c7-laptop-img2.jpeg",
        "processortype": "intel",
        "processorname": "corei7",
        "brand": "Microsoft",
        "batteryinfo": "up to 6hours",
        "ram": "16gb",
        "rom": "512 ssd",
        "windowversion": "windows 10",
        "color": "platinum",
        "touchscreen": "no",
        "netweight": "0.77kg",
        "inch": "12.3",
        "gaminggraphics": "Intel HD Graphics ",
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Microsoft Surface Pro 6 12.3' Intel Corei7 512GB/16GB..."
    },
    {
        "no": 77,
        "id": "c8-laptop",
        "productname": "Hp 240 G8 ",
        "productprice": "280,000",
        "productinfo": "Hp 240 G8 laptop",
        "productimage1": "/skydome images/c8-laptop-img1.jpeg",
        "productimage2": "/skydome images/c8-laptop-img2.jpeg",
        "processortype": "intel",
        "processorname": "corei3",
        "brand": "HP",
        "batteryinfo": "PowerAC adapter power45 W",
        "ram": "12gb",
        "rom": "1tb hdd",
        "windowversion": "windows 10 pro",
        "color": "Black",
        "touchscreen": "no",
        "netweight": "1.47kg",
        "inch": "12.8",
        "gaminggraphics": "Intel HD Graphics ",
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Hp 240 G8 Intel Core I3 10th Gen 1TB HDD 12GB RAM WIN 10.."
    },
    {
        "no": 78,
        "id": "c9-laptop",
        "productname": "Asus gaming pc",
        "productprice": "690,000",
        "productinfo": "Asus ROG STRIX gaming laptop",
        "productimage1": "/skydome images/c9-laptop-img1.jpeg",
        "productimage2": "/skydome images/c9-laptop-img2.jpeg",
        "processortype": "intel",
        "processorname": "corei7",
        "brand": "Asus",
        "batteryinfo": "1 Lithium ion battery",
        "ram": "16gb",
        "rom": "1tb ssd",
        "windowversion": "windows 10 home",
        "color": "Black",
        "touchscreen": "no",
        "netweight": "1.47kg",
        "inch": "15.6",
        "gaminggraphics": "NVIDIA GeForce GTX 1050 4GB graphics. Dual-fan thermal design",
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Asus ROG STRIX Gaming Laptop 15.6” Core I7-7700HQ 16GB..."
    },
    {
        "no": 79,
        "id": "c10-laptop",
        "productname": "DELL ALIENWARE",
        "productprice": "1,100,000",
        "productinfo": "DELL ALIENWARE M15 R3 9th generation laptop",
        "productimage1": "/skydome images/c10-laptop-img.png",
        "productimage2": "/skydome images/c10-laptop-img2.jpeg",
        "processortype": "intel",
        "processorname": "corei7",
        "brand": "DELL",
        "batteryinfo": "1 Lithium ion battery",
        "ram": "16gb",
        "rom": "512gb ssd",
        "windowversion": "windows 10 home",
        "color": "Black",
        "touchscreen": "no",
        "netweight": "4.7kg",
        "inch": "15.6",
        "gaminggraphics": "NVIDIA GeForce RTX 2060 6GB graphics and 6-phase voltage regulation",
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"DELL ALIENWARE M15 R3 - INTEL CORE I7-10750H, 15.6..."
    },
    {
        "no": 80,
        "id": "c11-laptop",
        "productname": "infinix INbook",
        "productprice": "470,000",
        "productinfo": "infinix INbook laptop",
        "productimage1": "/skydome images/c11-laptop-img1.Jpeg",
        "productimage2": "/skydome images/c11-laptop-img2.jpeg",
        "processortype": "intel",
        "processorname": "corei7",
        "brand": "INFINIX",
        "batteryinfo": " 55Wh battery Up to 13 Hours of Web Browsing",
        "ram": "16gb",
        "rom": "512gb ssd",
        "windowversion": "windows 10 home",
        "color": "Grey",
        "touchscreen": "no",
        "netweight": "1.4kg",
        "inch": "14",
        "gaminggraphics": "NVIDIA GeForce RTX 2060 6GB graphics and 6-phase voltage regulation",
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Infinix INBook Intel Core I7, 16GB RAM/512GB Ssd X1 Pro..."
    },
    {
        "no": 81,
        "id": "c12-laptop",
        "productname": "Hp Pavilion 15",
        "productprice": "495,000",
        "productinfo": "Pavilion 15 CONVERTIBLE laptop",
        "productimage1": "/skydome images/c12-laptop-img1.Jpeg",
        "productimage2": "/skydome images/c12-laptop-img2.jpeg",
        "processortype": "intel",
        "processorname": "corei7",
        "brand": "HP",
        "batteryinfo": "41.5Wh 3 cell Li-polymer battery",
        "ram": "8gb",
        "rom": "256gb ssd",
        "windowversion": "windows 10 home",
        "color": "Black and silver",
        "touchscreen": "Yes",
        "netweight": "1.32kg",
        "inch": "15.6",
        "gaminggraphics": "intel graphics",
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Pavilion 15 CONVERTIBLE,touch screen,corei7,8 generation.."
    }
]