export const ShoeProductDb=[
    {
        "no": 14,
        "id": "c9",
        "productname": "Nike airforce 1",
        "productprice": "20,000",
        "productinfo": null,
        "productimage1": "/skydome images/c9-shoe-img.png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"pink nike air force 1 shoe available in size 30-48"
    },
    {
        "no": 15,
        "id": "c10",
        "productname": "blue dior shoe",
        "productprice": "35,000",
        "productinfo": null,
        "productimage1": "/skydome images/c10-shoe-img.png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"blue dior shoes available in size 32-47"
    },
    {
        "no": 16,
        "id": "c11",
        "productname": "Air jordan 4",
        "productprice": "25,000",
        "productinfo": null,
        "productimage1": "/skydome images/c11-shoe-img.png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Air jordan 4 retro kaws grey available in size 40-52"
    },
    {
        "no": 17,
        "id": "c12",
        "productname": "Adidas yeezy boost",
        "productprice": "18,000",
        "productinfo": null,
        "productimage1": "/skydome images/c12-shoe-img.png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Adidas yeezy boost 350 v2 cloud white shoe"
    },
    {
        "no": 18,
        "id": "c13",
        "productname": "Female criss cross show",
        "productprice": "6,500",
        "productinfo": null,
        "productimage1": "/skydome images/c13-shoe-img.png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Criss Cross Open Toe Flat Sliders available in size..."
    },
    {
        "no": 19,
        "id": "c14",
        "productname": "Madden girl high heels",
        "productprice": "8,000",
        "productinfo": null,
        "productimage1": "/skydome images/c14-shoe-img.png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Madden girl high heels shoe available in size 27-32"
    },
    {
        "no": 20,
        "id": "c15",
        "productname": "Brown toe two strap heel",
        "productprice": "11,000",
        "productinfo": null,
        "productimage1": "/skydome images/c15-shoe-img.png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Brown toe two strap heel available in size 27-33"
    },
    {
        "no": 21,
        "id": "c16",
        "productname": "high sole sandals",
        "productprice": "9,000",
        "productinfo": null,
        "productimage1": "/skydome images/c16-shoe-img.png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"brown sewade high sole sandals"
    },
    {
        // shoes
        "no": 42,
        "id": "c1-shoe",
        "productname": "Vans shoe",
        "productprice": "14,000",
        "productinfo": null,
        "productimage1": "/skydome images/c1-shoe-img.Jpeg",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Vans X gremlin custom old skool shoe"
    },
    {
        "no": 43,
        "id": "c2-shoe",
        "productname": "Nike air jordan",
        "productprice": "25,000",
        "productinfo": null,
        "productimage1": "/skydome images/c2-shoe-img.Jpeg",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Nike air jordan 1 retro high sneakers"
    },
    {
        "no": 44,
        "id": "c3-shoe",
        "productname": "Nike airforce",
        "productprice": "17,000",
        "productinfo": null,
        "productimage1": "/skydome images/c3-shoe-img.png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"white nike airforce 1 shoe available in size 33-47"
    },
    {
        "no": 45,
        "id": "c4-shoe",
        "productname": "Puma shoe",
        "productprice": "11,000",
        "productinfo": null,
        "productimage1": "/skydome images/c4-shoe-img.Jpeg",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Puma RS-Z sneakers available in size 35-48"
    },
    {
        "no": 46,
        "id": "c5-shoe",
        "productname": "Louis vuitton shoe",
        "productprice": "34,000",
        "productinfo": null,
        "productimage1": "/skydome images/c5-shoe-img.png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Louis vuitton shoe available in size 33-47"
    },
    {
        "no": 48,
        "id": "c6-shoe",
        "productname": "Nike air jordan",
        "productprice": "28,000",
        "productinfo": null,
        "productimage1": "/skydome images/c6-shoe-img.png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Custom Nike air jordan sneakrs available in size 39-49"
    },
    {
        "no": 49,
        "id": "c7-shoe",
        "productname": "Jordan pro strong",
        "productprice": "13,000",
        "productinfo": null,
        "productimage1": "/skydome images/c7-shoe-img.Jpeg",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"White/Wolf Grey/Racer Blue Jordan pro strong shoe"
    },
    {
        "no": 51,
        "id": "c8-shoe",
        "productname": "Adidas yeezy boost",
        "productprice": "19,000",
        "productinfo": null,
        "productimage1": "/skydome images/c8-shoe-img.png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Adidas yeezy boost 350 v2 glow in the dark shoe"
    },
    {
        "no": 52,
        "id": "c9-shoe",
        "productname": "Channel shoe",
        "productprice": "32,000",
        "productinfo": null,
        "productimage1": "/skydome images/c9-shoe-img (2).png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"White pin on channel shoe available in size 27-38"
    },
    {
        "no": 53,
        "id": "c10-shoe",
        "productname": "White channel shoe",
        "productprice": "57,000",
        "productinfo": null,
        "productimage1": "/skydome images/c10-shoe-img (2).png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"pointed toe, pearl quilted pattern and embellished CC"
    },
    {
        "no": 54,
        "id": "c11-shoe",
        "productname": "Madden girl shoe",
        "productprice": "23,000",
        "productinfo": null,
        "productimage1": "/skydome images/c11-shoe-img.jpeg",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Yellow bella two-piece block heel sandals"
    },
    {
        "no": 55,
        "id": "c12-shoe",
        "productname": "Micheal kors",
        "productprice": "19,000",
        "productinfo": null,
        "productimage1": "/skydome images/c12-shoe-img.jpeg",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Womens imberly ankle strap dress sandals"
    },
    {
        "no": 56,
        "id": "c13-shoe",
        "productname": "Pink zara shoe",
        "productprice": "12,000",
        "productinfo": null,
        "productimage1": "/skydome images/c13-shoe-img (2).png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Pink zara transparent shoe availablein size 28-39"
    },
    {
        "no": 57,
        "id": "c14-shoe",
        "productname": "Bella Vita shoe",
        "productprice": "6,000",
        "productinfo": null,
        "productimage1": "/skydome images/c14-shoe-img.jpeg",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Bella Vita Womens Sarah Ii Slingback Dress Shoe Pump."
    },
    {
        "no": 58,
        "id": "c15-shoe",
        "productname": "Louis V sneakers.",
        "productprice": "19,000",
        "productinfo": null,
        "productimage1": "/skydome images/c15-shoe-img (2).png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Louis vouitton sneakers available in size 26-41."
    },
    {
        "no": 59,
        "id": "c16-shoe",
        "productname": "Channel boots",
        "productprice": "22,000",
        "productinfo": null,
        "productimage1": "/skydome images/c16-shoe-img (2).png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"black high leather channel female boots "
    },
    {
        "no": 60,
        "id": "c17-shoe",
        "productname": "Red suede tie shoe",
        "productprice": "16,000",
        "productinfo": null,
        "productimage1": "/skydome images/c17-shoe-img.png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Red suede tie shoe mens shoe available in size 35-51"
    },
    {
        "no": 61,
        "id": "c18-shoe",
        "productname": "Black seude shoe",
        "productprice": "15,000",
        "productinfo": null,
        "productimage1": "/skydome images/c18-shoe-img.png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"black mens seude coporate shoe available in size 36-46"
    },
    {
        "no": 62,
        "id": "c19-shoe",
        "productname": "Brown leather shoe",
        "productprice": "25,000",
        "productinfo": null,
        "productimage1": "/skydome images/c19-shoe-img.png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"brown  Oxfords Tassel Casual Genuine Leather Moccasins shoe"
    },
    {
        "no": 63,
        "id": "c20-shoe",
        "productname": "black seude shoe",
        "productprice": "13,000",
        "productinfo": null,
        "productimage1": "/skydome images/c20-shoe-img.png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"black mens seude coporate shoe available in size 36-46"
    },
    {
        "no": 64,
        "id": "c21-shoe",
        "productname": "Welcome slides",
        "productprice": "9,000",
        "productinfo": null,
        "productimage1": "/skydome images/c21-shoe-img.png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"welcome slides available in size 30-46"
    },
    {
        "no": 66,
        "id": "c22-shoe",
        "productname": "Adidas yeezy slide",
        "productprice": "9,000",
        "productinfo": null,
        "productimage1": "/skydome images/c22-shoe-img.Jpeg",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"gray Adidas yeezy slide bone available in size 30-48"
    },
    {
        "no": 67,
        "id": "c23-shoe",
        "productname": "Balenciaga loafer",
        "productprice": "29,000",
        "productinfo": null,
        "productimage1": "/skydome images/c23-shoe-img.png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Balenciaga loafer mule half shoe"
    },
    {
        "no": 68,
        "id": "c24-shoe",
        "productname": "Alexander mcQueen ",
        "productprice": "50,000",
        "productinfo": null,
        "productimage1": "/skydome images/c24-shoe-img.png",
        "productimage2": null,
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": null,
        "ram": null,
        "rom": null,
        "windowversion": null,
        "color": null,
        "touchscreen": null,
        "netweight": null,
        "inch": null,
        "gaminggraphics": null,
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "productinfopreview":"Unisex Alexander mcQueen sneakers"
    }
]